name: Warmup Cache

on:
  schedule:
    - cron: '0 0 * * *' # Będzie się uruchamiać codziennie o północy UTC
  workflow_dispatch:

jobs:
  ping-endpoint:
    runs-on: ubuntu-latest
    name: Generate Cloudflare Stats
    steps:
      - name: Ping the stats endpoint to warm up cache
        run: |
          echo "Warming up https://dav.one/cloudflare-stats.json"
          curl -sS https://dav.one/cloudflare-stats.json > /dev/null
          echo "Cache warmed successfully!"
